name: maids_tasks_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Network
  dio: ^5.4.2+1

  # Routing
  auto_route: ^8.0.3
  flutter_phoenix: ^1.1.1
  
  # BLOC
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.8
  bloc_test: ^9.1.7
  
  # Storage
  shared_preferences: ^2.2.2

  # Pagination
  infinite_scroll_pagination: ^4.0.0

  # Image 
  cached_network_image: ^3.3.1
  path: ^1.9.0
  sqflite: ^2.3.3

  # Test
  mockito: ^5.4.4
  mocktail: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  
flutter:
  uses-material-design: true
